// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/files.proto

// buf:lint:ignore PACKAGE_DIRECTORY_MATCH

package apipb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPresignedURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileId        string                 `protobuf:"bytes,5,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLRequest) Reset() {
	*x = GetPresignedURLRequest{}
	mi := &file_api_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLRequest) ProtoMessage() {}

func (x *GetPresignedURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedURLRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *GetPresignedURLRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetPresignedURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetPresignedURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetPresignedURLRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetPresignedURLRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetPresignedURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PresignedUrl  string                 `protobuf:"bytes,1,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ExposedUrl    string                 `protobuf:"bytes,3,opt,name=exposed_url,json=exposedUrl,proto3" json:"exposed_url,omitempty"`
	FileId        string                 `protobuf:"bytes,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedURLResponse) Reset() {
	*x = GetPresignedURLResponse{}
	mi := &file_api_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedURLResponse) ProtoMessage() {}

func (x *GetPresignedURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedURLResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedURLResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *GetPresignedURLResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *GetPresignedURLResponse) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GetPresignedURLResponse) GetExposedUrl() string {
	if x != nil {
		return x.ExposedUrl
	}
	return ""
}

func (x *GetPresignedURLResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

var File_api_v1_files_proto protoreflect.FileDescriptor

const file_api_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/files.proto\x12\x0eskyline.api.v1\x1a\x1cgoogle/api/annotations.proto\"\xa3\x01\n" +
	"\x16GetPresignedURLRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\x12\x17\n" +
	"\afile_id\x18\x05 \x01(\tR\x06fileId\"\x95\x01\n" +
	"\x17GetPresignedURLResponse\x12#\n" +
	"\rpresigned_url\x18\x01 \x01(\tR\fpresignedUrl\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vexposed_url\x18\x03 \x01(\tR\n" +
	"exposedUrl\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\tR\x06fileId2\x95\x01\n" +
	"\fFilesService\x12\x84\x01\n" +
	"\x0fGetPresignedURL\x12&.skyline.api.v1.GetPresignedURLRequest\x1a'.skyline.api.v1.GetPresignedURLResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/files/presigned-urlsB>Z<github.com/lynx-go/lynx-clean-template/genproto/api/v1;apipbb\x06proto3"

var (
	file_api_v1_files_proto_rawDescOnce sync.Once
	file_api_v1_files_proto_rawDescData []byte
)

func file_api_v1_files_proto_rawDescGZIP() []byte {
	file_api_v1_files_proto_rawDescOnce.Do(func() {
		file_api_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_files_proto_rawDesc), len(file_api_v1_files_proto_rawDesc)))
	})
	return file_api_v1_files_proto_rawDescData
}

var file_api_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_files_proto_goTypes = []any{
	(*GetPresignedURLRequest)(nil),  // 0: skyline.api.v1.GetPresignedURLRequest
	(*GetPresignedURLResponse)(nil), // 1: skyline.api.v1.GetPresignedURLResponse
}
var file_api_v1_files_proto_depIdxs = []int32{
	0, // 0: skyline.api.v1.FilesService.GetPresignedURL:input_type -> skyline.api.v1.GetPresignedURLRequest
	1, // 1: skyline.api.v1.FilesService.GetPresignedURL:output_type -> skyline.api.v1.GetPresignedURLResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_files_proto_init() }
func file_api_v1_files_proto_init() {
	if File_api_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_files_proto_rawDesc), len(file_api_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_files_proto_goTypes,
		DependencyIndexes: file_api_v1_files_proto_depIdxs,
		MessageInfos:      file_api_v1_files_proto_msgTypes,
	}.Build()
	File_api_v1_files_proto = out.File
	file_api_v1_files_proto_goTypes = nil
	file_api_v1_files_proto_depIdxs = nil
}
