// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/v1/users.proto

package apipb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/lynx-go/lynx-clean-template/genproto/shared"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User represents a user profile
type UserProfile struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username     string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName  string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl    string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Phone        string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email        string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Gender       int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Status       int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastSignInAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_sign_in_at,json=lastSignInAt,proto3" json:"last_sign_in_at,omitempty"`
	BannedUntil  *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=banned_until,json=bannedUntil,proto3" json:"banned_until,omitempty"`
	IsSuperAdmin bool                   `protobuf:"varint,13,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	// Metadata fields
	UserMetadata  *shared.UserMetadata `protobuf:"bytes,21,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	AppMetadata   *shared.AppMetadata  `protobuf:"bytes,22,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserProfile) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserProfile) GetLastSignInAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSignInAt
	}
	return nil
}

func (x *UserProfile) GetBannedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.BannedUntil
	}
	return nil
}

func (x *UserProfile) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *UserProfile) GetUserMetadata() *shared.UserMetadata {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *UserProfile) GetAppMetadata() *shared.AppMetadata {
	if x != nil {
		return x.AppMetadata
	}
	return nil
}

// UpdateMyProfileRequest contains the fields to update
type UpdateMyProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserProfile           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMyProfileRequest) Reset() {
	*x = UpdateMyProfileRequest{}
	mi := &file_api_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMyProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMyProfileRequest) ProtoMessage() {}

func (x *UpdateMyProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMyProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateMyProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateMyProfileRequest) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateMyProfileRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// GetUserProfileRequest contains the user ID to query
// When user_id is "-", returns the authenticated user's profile
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_api_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GrantSuperAdminRequest contains the target user ID to grant super admin.
type GrantSuperAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantSuperAdminRequest) Reset() {
	*x = GrantSuperAdminRequest{}
	mi := &file_api_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantSuperAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantSuperAdminRequest) ProtoMessage() {}

func (x *GrantSuperAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantSuperAdminRequest.ProtoReflect.Descriptor instead.
func (*GrantSuperAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *GrantSuperAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RevokeSuperAdminRequest contains the target user ID to revoke super admin.
type RevokeSuperAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSuperAdminRequest) Reset() {
	*x = RevokeSuperAdminRequest{}
	mi := &file_api_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSuperAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSuperAdminRequest) ProtoMessage() {}

func (x *RevokeSuperAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSuperAdminRequest.ProtoReflect.Descriptor instead.
func (*RevokeSuperAdminRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_users_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeSuperAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_v1_users_proto protoreflect.FileDescriptor

const file_api_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/users.proto\x12\vlynx.api.v1\x1a\x11shared/user.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xf2\x04\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x0flast_sign_in_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastSignInAt\x12=\n" +
	"\fbanned_until\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vbannedUntil\x12$\n" +
	"\x0eis_super_admin\x18\r \x01(\bR\fisSuperAdmin\x12>\n" +
	"\ruser_metadata\x18\x15 \x01(\v2\x19.lynx.shared.UserMetadataR\fuserMetadata\x12;\n" +
	"\fapp_metadata\x18\x16 \x01(\v2\x18.lynx.shared.AppMetadataR\vappMetadata\"\x83\x01\n" +
	"\x16UpdateMyProfileRequest\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.lynx.api.v1.UserProfileR\x04user\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"8\n" +
	"\x15GetUserProfileRequest\x12\x1f\n" +
	"\auser_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06userId\"9\n" +
	"\x16GrantSuperAdminRequest\x12\x1f\n" +
	"\auser_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06userId\":\n" +
	"\x17RevokeSuperAdminRequest\x12\x1f\n" +
	"\auser_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06userId2\x81\x04\n" +
	"\fUsersService\x12s\n" +
	"\x0fUpdateMyProfile\x12#.lynx.api.v1.UpdateMyProfileRequest\x1a\x18.lynx.api.v1.UserProfile\"!\x82\xd3\xe4\x93\x02\x1b:\x04user2\x13/v1/users/-/profile\x12s\n" +
	"\x0eGetUserProfile\x12\".lynx.api.v1.GetUserProfileRequest\x1a\x18.lynx.api.v1.UserProfile\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/profile\x12\x82\x01\n" +
	"\x0fGrantSuperAdmin\x12#.lynx.api.v1.GrantSuperAdminRequest\x1a\x18.lynx.api.v1.UserProfile\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/admin/users/{user_id}/super-admin\x12\x81\x01\n" +
	"\x10RevokeSuperAdmin\x12$.lynx.api.v1.RevokeSuperAdminRequest\x1a\x18.lynx.api.v1.UserProfile\"-\x82\xd3\xe4\x93\x02'*%/v1/admin/users/{user_id}/super-adminB>Z<github.com/lynx-go/lynx-clean-template/genproto/api/v1;apipbb\x06proto3"

var (
	file_api_v1_users_proto_rawDescOnce sync.Once
	file_api_v1_users_proto_rawDescData []byte
)

func file_api_v1_users_proto_rawDescGZIP() []byte {
	file_api_v1_users_proto_rawDescOnce.Do(func() {
		file_api_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_users_proto_rawDesc), len(file_api_v1_users_proto_rawDesc)))
	})
	return file_api_v1_users_proto_rawDescData
}

var file_api_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_users_proto_goTypes = []any{
	(*UserProfile)(nil),             // 0: lynx.api.v1.UserProfile
	(*UpdateMyProfileRequest)(nil),  // 1: lynx.api.v1.UpdateMyProfileRequest
	(*GetUserProfileRequest)(nil),   // 2: lynx.api.v1.GetUserProfileRequest
	(*GrantSuperAdminRequest)(nil),  // 3: lynx.api.v1.GrantSuperAdminRequest
	(*RevokeSuperAdminRequest)(nil), // 4: lynx.api.v1.RevokeSuperAdminRequest
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*shared.UserMetadata)(nil),     // 6: lynx.shared.UserMetadata
	(*shared.AppMetadata)(nil),      // 7: lynx.shared.AppMetadata
	(*fieldmaskpb.FieldMask)(nil),   // 8: google.protobuf.FieldMask
}
var file_api_v1_users_proto_depIdxs = []int32{
	5,  // 0: lynx.api.v1.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	5,  // 1: lynx.api.v1.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 2: lynx.api.v1.UserProfile.last_sign_in_at:type_name -> google.protobuf.Timestamp
	5,  // 3: lynx.api.v1.UserProfile.banned_until:type_name -> google.protobuf.Timestamp
	6,  // 4: lynx.api.v1.UserProfile.user_metadata:type_name -> lynx.shared.UserMetadata
	7,  // 5: lynx.api.v1.UserProfile.app_metadata:type_name -> lynx.shared.AppMetadata
	0,  // 6: lynx.api.v1.UpdateMyProfileRequest.user:type_name -> lynx.api.v1.UserProfile
	8,  // 7: lynx.api.v1.UpdateMyProfileRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 8: lynx.api.v1.UsersService.UpdateMyProfile:input_type -> lynx.api.v1.UpdateMyProfileRequest
	2,  // 9: lynx.api.v1.UsersService.GetUserProfile:input_type -> lynx.api.v1.GetUserProfileRequest
	3,  // 10: lynx.api.v1.UsersService.GrantSuperAdmin:input_type -> lynx.api.v1.GrantSuperAdminRequest
	4,  // 11: lynx.api.v1.UsersService.RevokeSuperAdmin:input_type -> lynx.api.v1.RevokeSuperAdminRequest
	0,  // 12: lynx.api.v1.UsersService.UpdateMyProfile:output_type -> lynx.api.v1.UserProfile
	0,  // 13: lynx.api.v1.UsersService.GetUserProfile:output_type -> lynx.api.v1.UserProfile
	0,  // 14: lynx.api.v1.UsersService.GrantSuperAdmin:output_type -> lynx.api.v1.UserProfile
	0,  // 15: lynx.api.v1.UsersService.RevokeSuperAdmin:output_type -> lynx.api.v1.UserProfile
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_users_proto_init() }
func file_api_v1_users_proto_init() {
	if File_api_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_users_proto_rawDesc), len(file_api_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_users_proto_goTypes,
		DependencyIndexes: file_api_v1_users_proto_depIdxs,
		MessageInfos:      file_api_v1_users_proto_msgTypes,
	}.Build()
	File_api_v1_users_proto = out.File
	file_api_v1_users_proto_goTypes = nil
	file_api_v1_users_proto_depIdxs = nil
}
