// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package tests

import (
	"github.com/lynx-go/lynx"
)

// Injectors from wire.go:

func wireTestingSuite(app lynx.Lynx) (*TestingSuite, func(), error) {
	testingSuite := NewTestingSuite()
	return testingSuite, func() {
	}, nil
}
