// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Pubsub        *PubSub                `protobuf:"bytes,3,opt,name=pubsub,proto3" json:"pubsub,omitempty"`
	Security      *Security              `protobuf:"bytes,4,opt,name=security,proto3" json:"security,omitempty"`
	File          *File                  `protobuf:"bytes,5,opt,name=file,proto3" json:"file,omitempty"`
	App           *App                   `protobuf:"bytes,6,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfig) Reset() {
	*x = AppConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfig) ProtoMessage() {}

func (x *AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *AppConfig) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *AppConfig) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AppConfig) GetPubsub() *PubSub {
	if x != nil {
		return x.Pubsub
	}
	return nil
}

func (x *AppConfig) GetSecurity() *Security {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *AppConfig) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *AppConfig) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Http            *Http                  `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc            *GRPC                  `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	AiGateway       *Http                  `protobuf:"bytes,3,opt,name=ai_gateway,json=aiGateway,proto3" json:"ai_gateway,omitempty"`
	MessageloopGrpc *GRPC                  `protobuf:"bytes,4,opt,name=messageloop_grpc,json=messageloopGrpc,proto3" json:"messageloop_grpc,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Http {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAiGateway() *Http {
	if x != nil {
		return x.AiGateway
	}
	return nil
}

func (x *Server) GetMessageloopGrpc() *GRPC {
	if x != nil {
		return x.MessageloopGrpc
	}
	return nil
}

type Security struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           *Security_Jwt          `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Security) Reset() {
	*x = Security{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security) ProtoMessage() {}

func (x *Security) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security.ProtoReflect.Descriptor instead.
func (*Security) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Security) GetJwt() *Security_Jwt {
	if x != nil {
		return x.Jwt
	}
	return nil
}

type GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GRPC) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Http struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Cors          *Http_Cors             `protobuf:"bytes,4,opt,name=cors,proto3" json:"cors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Http) Reset() {
	*x = Http{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *Http) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Http) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Http) GetCors() *Http_Cors {
	if x != nil {
		return x.Cors
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Dialect       string                 `protobuf:"bytes,2,opt,name=dialect,proto3" json:"dialect,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	Pool          *Database_Pool         `protobuf:"bytes,5,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Database) GetDialect() string {
	if x != nil {
		return x.Dialect
	}
	return ""
}

func (x *Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Database) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Database) GetPool() *Database_Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type PubSub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kafka         map[string]*Kafka      `protobuf:"bytes,1,rep,name=kafka,proto3" json:"kafka,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubSub) Reset() {
	*x = PubSub{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubSub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubSub) ProtoMessage() {}

func (x *PubSub) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubSub.ProtoReflect.Descriptor instead.
func (*PubSub) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *PubSub) GetKafka() map[string]*Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Consumer      *Kafka_Consumer        `protobuf:"bytes,3,opt,name=consumer,proto3" json:"consumer,omitempty"`
	Producer      *Kafka_Producer        `protobuf:"bytes,4,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka) Reset() {
	*x = Kafka{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka) ProtoMessage() {}

func (x *Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka.ProtoReflect.Descriptor instead.
func (*Kafka) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Kafka) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Kafka) GetConsumer() *Kafka_Consumer {
	if x != nil {
		return x.Consumer
	}
	return nil
}

func (x *Kafka) GetProducer() *Kafka_Producer {
	if x != nil {
		return x.Producer
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Buckets       map[string]*File_Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *File) GetBuckets() map[string]*File_Bucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *App) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DefaultAvatarUrls []string               `protobuf:"bytes,1,rep,name=default_avatar_urls,json=defaultAvatarUrls,proto3" json:"default_avatar_urls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{12}
}

func (x *User) GetDefaultAvatarUrls() []string {
	if x != nil {
		return x.DefaultAvatarUrls
	}
	return nil
}

type Security_Jwt struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Secret                string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	TokenExpirySec        int32                  `protobuf:"varint,2,opt,name=token_expiry_sec,json=tokenExpirySec,proto3" json:"token_expiry_sec,omitempty"`
	RefreshTokenSecret    string                 `protobuf:"bytes,3,opt,name=refresh_token_secret,json=refreshTokenSecret,proto3" json:"refresh_token_secret,omitempty"`
	RefreshTokenExpirySec int32                  `protobuf:"varint,4,opt,name=refresh_token_expiry_sec,json=refreshTokenExpirySec,proto3" json:"refresh_token_expiry_sec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Security_Jwt) Reset() {
	*x = Security_Jwt{}
	mi := &file_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Security_Jwt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Security_Jwt) ProtoMessage() {}

func (x *Security_Jwt) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Security_Jwt.ProtoReflect.Descriptor instead.
func (*Security_Jwt) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Security_Jwt) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Security_Jwt) GetTokenExpirySec() int32 {
	if x != nil {
		return x.TokenExpirySec
	}
	return 0
}

func (x *Security_Jwt) GetRefreshTokenSecret() string {
	if x != nil {
		return x.RefreshTokenSecret
	}
	return ""
}

func (x *Security_Jwt) GetRefreshTokenExpirySec() int32 {
	if x != nil {
		return x.RefreshTokenExpirySec
	}
	return 0
}

type Http_Cors struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AllowOrigins     []string               `protobuf:"bytes,1,rep,name=allow_origins,json=allowOrigins,proto3" json:"allow_origins,omitempty"`
	AllowMethods     []string               `protobuf:"bytes,2,rep,name=allow_methods,json=allowMethods,proto3" json:"allow_methods,omitempty"`
	AllowHeaders     []string               `protobuf:"bytes,3,rep,name=allow_headers,json=allowHeaders,proto3" json:"allow_headers,omitempty"`
	ExposeHeaders    []string               `protobuf:"bytes,4,rep,name=expose_headers,json=exposeHeaders,proto3" json:"expose_headers,omitempty"`
	AllowCredentials bool                   `protobuf:"varint,5,opt,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	MaxAge           int32                  `protobuf:"varint,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Http_Cors) Reset() {
	*x = Http_Cors{}
	mi := &file_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Http_Cors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http_Cors) ProtoMessage() {}

func (x *Http_Cors) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http_Cors.ProtoReflect.Descriptor instead.
func (*Http_Cors) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Http_Cors) GetAllowOrigins() []string {
	if x != nil {
		return x.AllowOrigins
	}
	return nil
}

func (x *Http_Cors) GetAllowMethods() []string {
	if x != nil {
		return x.AllowMethods
	}
	return nil
}

func (x *Http_Cors) GetAllowHeaders() []string {
	if x != nil {
		return x.AllowHeaders
	}
	return nil
}

func (x *Http_Cors) GetExposeHeaders() []string {
	if x != nil {
		return x.ExposeHeaders
	}
	return nil
}

func (x *Http_Cors) GetAllowCredentials() bool {
	if x != nil {
		return x.AllowCredentials
	}
	return false
}

func (x *Http_Cors) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

type Database_Pool struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MaxIdleConns    int32                  `protobuf:"varint,1,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,2,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	ConnMaxLifetime string                 `protobuf:"bytes,3,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	ConnMaxIdleTime string                 `protobuf:"bytes,4,opt,name=conn_max_idle_time,json=connMaxIdleTime,proto3" json:"conn_max_idle_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Database_Pool) Reset() {
	*x = Database_Pool{}
	mi := &file_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database_Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database_Pool) ProtoMessage() {}

func (x *Database_Pool) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database_Pool.ProtoReflect.Descriptor instead.
func (*Database_Pool) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Database_Pool) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Database_Pool) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Database_Pool) GetConnMaxLifetime() string {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return ""
}

func (x *Database_Pool) GetConnMaxIdleTime() string {
	if x != nil {
		return x.ConnMaxIdleTime
	}
	return ""
}

type Kafka_Consumer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	StartOffset   int32                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	Instances     int32                  `protobuf:"varint,3,opt,name=instances,proto3" json:"instances,omitempty"`
	LogMessage    bool                   `protobuf:"varint,4,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	MappedEvent   string                 `protobuf:"bytes,5,opt,name=mapped_event,json=mappedEvent,proto3" json:"mapped_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka_Consumer) Reset() {
	*x = Kafka_Consumer{}
	mi := &file_config_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Consumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Consumer) ProtoMessage() {}

func (x *Kafka_Consumer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Consumer.ProtoReflect.Descriptor instead.
func (*Kafka_Consumer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 0}
}

func (x *Kafka_Consumer) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Kafka_Consumer) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *Kafka_Consumer) GetInstances() int32 {
	if x != nil {
		return x.Instances
	}
	return 0
}

func (x *Kafka_Consumer) GetLogMessage() bool {
	if x != nil {
		return x.LogMessage
	}
	return false
}

func (x *Kafka_Consumer) GetMappedEvent() string {
	if x != nil {
		return x.MappedEvent
	}
	return ""
}

type Kafka_Producer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          int32                  `protobuf:"varint,1,opt,name=acks,proto3" json:"acks,omitempty"`
	LogMessage    bool                   `protobuf:"varint,2,opt,name=log_message,json=logMessage,proto3" json:"log_message,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchTimeout  string                 `protobuf:"bytes,4,opt,name=batch_timeout,json=batchTimeout,proto3" json:"batch_timeout,omitempty"`
	MappedEvent   string                 `protobuf:"bytes,5,opt,name=mapped_event,json=mappedEvent,proto3" json:"mapped_event,omitempty"`
	Async         bool                   `protobuf:"varint,6,opt,name=async,proto3" json:"async,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kafka_Producer) Reset() {
	*x = Kafka_Producer{}
	mi := &file_config_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kafka_Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kafka_Producer) ProtoMessage() {}

func (x *Kafka_Producer) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kafka_Producer.ProtoReflect.Descriptor instead.
func (*Kafka_Producer) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9, 1}
}

func (x *Kafka_Producer) GetAcks() int32 {
	if x != nil {
		return x.Acks
	}
	return 0
}

func (x *Kafka_Producer) GetLogMessage() bool {
	if x != nil {
		return x.LogMessage
	}
	return false
}

func (x *Kafka_Producer) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *Kafka_Producer) GetBatchTimeout() string {
	if x != nil {
		return x.BatchTimeout
	}
	return ""
}

func (x *Kafka_Producer) GetMappedEvent() string {
	if x != nil {
		return x.MappedEvent
	}
	return ""
}

func (x *Kafka_Producer) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type File_Bucket struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Endpoint          string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	BucketName        string                 `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	AccessKeyId       string                 `protobuf:"bytes,3,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	AccessKeySecret   string                 `protobuf:"bytes,4,opt,name=access_key_secret,json=accessKeySecret,proto3" json:"access_key_secret,omitempty"`
	RegionName        string                 `protobuf:"bytes,5,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	Url               string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	BasePath          string                 `protobuf:"bytes,7,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	ExposedUrl        string                 `protobuf:"bytes,10,opt,name=exposed_url,json=exposedUrl,proto3" json:"exposed_url,omitempty"`
	IncludeCategories []string               `protobuf:"bytes,11,rep,name=include_categories,json=includeCategories,proto3" json:"include_categories,omitempty"`
	FilePathTemplates map[string]string      `protobuf:"bytes,12,rep,name=file_path_templates,json=filePathTemplates,proto3" json:"file_path_templates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *File_Bucket) Reset() {
	*x = File_Bucket{}
	mi := &file_config_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File_Bucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File_Bucket) ProtoMessage() {}

func (x *File_Bucket) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File_Bucket.ProtoReflect.Descriptor instead.
func (*File_Bucket) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10, 0}
}

func (x *File_Bucket) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *File_Bucket) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *File_Bucket) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *File_Bucket) GetAccessKeySecret() string {
	if x != nil {
		return x.AccessKeySecret
	}
	return ""
}

func (x *File_Bucket) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *File_Bucket) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *File_Bucket) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *File_Bucket) GetExposedUrl() string {
	if x != nil {
		return x.ExposedUrl
	}
	return ""
}

func (x *File_Bucket) GetIncludeCategories() []string {
	if x != nil {
		return x.IncludeCategories
	}
	return nil
}

func (x *File_Bucket) GetFilePathTemplates() map[string]string {
	if x != nil {
		return x.FilePathTemplates
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x12skyline.api.config\"\xb4\x02\n" +
	"\tAppConfig\x122\n" +
	"\x06server\x18\x01 \x01(\v2\x1a.skyline.api.config.ServerR\x06server\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.skyline.api.config.DataR\x04data\x122\n" +
	"\x06pubsub\x18\x03 \x01(\v2\x1a.skyline.api.config.PubSubR\x06pubsub\x128\n" +
	"\bsecurity\x18\x04 \x01(\v2\x1c.skyline.api.config.SecurityR\bsecurity\x12,\n" +
	"\x04file\x18\x05 \x01(\v2\x18.skyline.api.config.FileR\x04file\x12)\n" +
	"\x03app\x18\x06 \x01(\v2\x17.skyline.api.config.AppR\x03app\"\xe2\x01\n" +
	"\x06Server\x12,\n" +
	"\x04http\x18\x01 \x01(\v2\x18.skyline.api.config.HttpR\x04http\x12,\n" +
	"\x04grpc\x18\x02 \x01(\v2\x18.skyline.api.config.GRPCR\x04grpc\x127\n" +
	"\n" +
	"ai_gateway\x18\x03 \x01(\v2\x18.skyline.api.config.HttpR\taiGateway\x12C\n" +
	"\x10messageloop_grpc\x18\x04 \x01(\v2\x18.skyline.api.config.GRPCR\x0fmessageloopGrpc\"\xf3\x01\n" +
	"\bSecurity\x122\n" +
	"\x03jwt\x18\x01 \x01(\v2 .skyline.api.config.Security.JwtR\x03jwt\x1a\xb2\x01\n" +
	"\x03Jwt\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12(\n" +
	"\x10token_expiry_sec\x18\x02 \x01(\x05R\x0etokenExpirySec\x120\n" +
	"\x14refresh_token_secret\x18\x03 \x01(\tR\x12refreshTokenSecret\x127\n" +
	"\x18refresh_token_expiry_sec\x18\x04 \x01(\x05R\x15refreshTokenExpirySec\"4\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\"\xcc\x02\n" +
	"\x04Http\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\x121\n" +
	"\x04cors\x18\x04 \x01(\v2\x1d.skyline.api.config.Http.CorsR\x04cors\x1a\xe2\x01\n" +
	"\x04Cors\x12#\n" +
	"\rallow_origins\x18\x01 \x03(\tR\fallowOrigins\x12#\n" +
	"\rallow_methods\x18\x02 \x03(\tR\fallowMethods\x12#\n" +
	"\rallow_headers\x18\x03 \x03(\tR\fallowHeaders\x12%\n" +
	"\x0eexpose_headers\x18\x04 \x03(\tR\rexposeHeaders\x12+\n" +
	"\x11allow_credentials\x18\x05 \x01(\bR\x10allowCredentials\x12\x17\n" +
	"\amax_age\x18\x06 \x01(\x05R\x06maxAge\"\xcf\x02\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x18\n" +
	"\adialect\x18\x02 \x01(\tR\adialect\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\x125\n" +
	"\x04pool\x18\x05 \x01(\v2!.skyline.api.config.Database.PoolR\x04pool\x1a\xab\x01\n" +
	"\x04Pool\x12$\n" +
	"\x0emax_idle_conns\x18\x01 \x01(\x05R\fmaxIdleConns\x12$\n" +
	"\x0emax_open_conns\x18\x02 \x01(\x05R\fmaxOpenConns\x12*\n" +
	"\x11conn_max_lifetime\x18\x03 \x01(\tR\x0fconnMaxLifetime\x12+\n" +
	"\x12conn_max_idle_time\x18\x04 \x01(\tR\x0fconnMaxIdleTime\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"q\n" +
	"\x04Data\x128\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1c.skyline.api.config.DatabaseR\bdatabase\x12/\n" +
	"\x05redis\x18\x02 \x01(\v2\x19.skyline.api.config.RedisR\x05redis\"\x9a\x01\n" +
	"\x06PubSub\x12;\n" +
	"\x05kafka\x18\x01 \x03(\v2%.skyline.api.config.PubSub.KafkaEntryR\x05kafka\x1aS\n" +
	"\n" +
	"KafkaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.skyline.api.config.KafkaR\x05value:\x028\x01\"\xa3\x04\n" +
	"\x05Kafka\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12>\n" +
	"\bconsumer\x18\x03 \x01(\v2\".skyline.api.config.Kafka.ConsumerR\bconsumer\x12>\n" +
	"\bproducer\x18\x04 \x01(\v2\".skyline.api.config.Kafka.ProducerR\bproducer\x1a\xaa\x01\n" +
	"\bConsumer\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x05R\vstartOffset\x12\x1c\n" +
	"\tinstances\x18\x03 \x01(\x05R\tinstances\x12\x1f\n" +
	"\vlog_message\x18\x04 \x01(\bR\n" +
	"logMessage\x12!\n" +
	"\fmapped_event\x18\x05 \x01(\tR\vmappedEvent\x1a\xbc\x01\n" +
	"\bProducer\x12\x12\n" +
	"\x04acks\x18\x01 \x01(\x05R\x04acks\x12\x1f\n" +
	"\vlog_message\x18\x02 \x01(\bR\n" +
	"logMessage\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12#\n" +
	"\rbatch_timeout\x18\x04 \x01(\tR\fbatchTimeout\x12!\n" +
	"\fmapped_event\x18\x05 \x01(\tR\vmappedEvent\x12\x14\n" +
	"\x05async\x18\x06 \x01(\bR\x05async\"\x8a\x05\n" +
	"\x04File\x12?\n" +
	"\abuckets\x18\x01 \x03(\v2%.skyline.api.config.File.BucketsEntryR\abuckets\x1a\xe3\x03\n" +
	"\x06Bucket\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vbucket_name\x18\x02 \x01(\tR\n" +
	"bucketName\x12\"\n" +
	"\raccess_key_id\x18\x03 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11access_key_secret\x18\x04 \x01(\tR\x0faccessKeySecret\x12\x1f\n" +
	"\vregion_name\x18\x05 \x01(\tR\n" +
	"regionName\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1b\n" +
	"\tbase_path\x18\a \x01(\tR\bbasePath\x12\x1f\n" +
	"\vexposed_url\x18\n" +
	" \x01(\tR\n" +
	"exposedUrl\x12-\n" +
	"\x12include_categories\x18\v \x03(\tR\x11includeCategories\x12f\n" +
	"\x13file_path_templates\x18\f \x03(\v26.skyline.api.config.File.Bucket.FilePathTemplatesEntryR\x11filePathTemplates\x1aD\n" +
	"\x16FilePathTemplatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a[\n" +
	"\fBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.skyline.api.config.File.BucketR\x05value:\x028\x01\"3\n" +
	"\x03App\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.skyline.api.config.UserR\x04user\"6\n" +
	"\x04User\x12.\n" +
	"\x13default_avatar_urls\x18\x01 \x03(\tR\x11defaultAvatarUrlsB2Z0github.com/lynx-go/lynx-clean-template/internal/pkg/configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_config_proto_goTypes = []any{
	(*AppConfig)(nil),      // 0: skyline.api.config.AppConfig
	(*Server)(nil),         // 1: skyline.api.config.Server
	(*Security)(nil),       // 2: skyline.api.config.Security
	(*GRPC)(nil),           // 3: skyline.api.config.GRPC
	(*Http)(nil),           // 4: skyline.api.config.Http
	(*Database)(nil),       // 5: skyline.api.config.Database
	(*Redis)(nil),          // 6: skyline.api.config.Redis
	(*Data)(nil),           // 7: skyline.api.config.Data
	(*PubSub)(nil),         // 8: skyline.api.config.PubSub
	(*Kafka)(nil),          // 9: skyline.api.config.Kafka
	(*File)(nil),           // 10: skyline.api.config.File
	(*App)(nil),            // 11: skyline.api.config.App
	(*User)(nil),           // 12: skyline.api.config.User
	(*Security_Jwt)(nil),   // 13: skyline.api.config.Security.Jwt
	(*Http_Cors)(nil),      // 14: skyline.api.config.Http.Cors
	(*Database_Pool)(nil),  // 15: skyline.api.config.Database.Pool
	nil,                    // 16: skyline.api.config.PubSub.KafkaEntry
	(*Kafka_Consumer)(nil), // 17: skyline.api.config.Kafka.Consumer
	(*Kafka_Producer)(nil), // 18: skyline.api.config.Kafka.Producer
	(*File_Bucket)(nil),    // 19: skyline.api.config.File.Bucket
	nil,                    // 20: skyline.api.config.File.BucketsEntry
	nil,                    // 21: skyline.api.config.File.Bucket.FilePathTemplatesEntry
}
var file_config_proto_depIdxs = []int32{
	1,  // 0: skyline.api.config.AppConfig.server:type_name -> skyline.api.config.Server
	7,  // 1: skyline.api.config.AppConfig.data:type_name -> skyline.api.config.Data
	8,  // 2: skyline.api.config.AppConfig.pubsub:type_name -> skyline.api.config.PubSub
	2,  // 3: skyline.api.config.AppConfig.security:type_name -> skyline.api.config.Security
	10, // 4: skyline.api.config.AppConfig.file:type_name -> skyline.api.config.File
	11, // 5: skyline.api.config.AppConfig.app:type_name -> skyline.api.config.App
	4,  // 6: skyline.api.config.Server.http:type_name -> skyline.api.config.Http
	3,  // 7: skyline.api.config.Server.grpc:type_name -> skyline.api.config.GRPC
	4,  // 8: skyline.api.config.Server.ai_gateway:type_name -> skyline.api.config.Http
	3,  // 9: skyline.api.config.Server.messageloop_grpc:type_name -> skyline.api.config.GRPC
	13, // 10: skyline.api.config.Security.jwt:type_name -> skyline.api.config.Security.Jwt
	14, // 11: skyline.api.config.Http.cors:type_name -> skyline.api.config.Http.Cors
	15, // 12: skyline.api.config.Database.pool:type_name -> skyline.api.config.Database.Pool
	5,  // 13: skyline.api.config.Data.database:type_name -> skyline.api.config.Database
	6,  // 14: skyline.api.config.Data.redis:type_name -> skyline.api.config.Redis
	16, // 15: skyline.api.config.PubSub.kafka:type_name -> skyline.api.config.PubSub.KafkaEntry
	17, // 16: skyline.api.config.Kafka.consumer:type_name -> skyline.api.config.Kafka.Consumer
	18, // 17: skyline.api.config.Kafka.producer:type_name -> skyline.api.config.Kafka.Producer
	20, // 18: skyline.api.config.File.buckets:type_name -> skyline.api.config.File.BucketsEntry
	12, // 19: skyline.api.config.App.user:type_name -> skyline.api.config.User
	9,  // 20: skyline.api.config.PubSub.KafkaEntry.value:type_name -> skyline.api.config.Kafka
	21, // 21: skyline.api.config.File.Bucket.file_path_templates:type_name -> skyline.api.config.File.Bucket.FilePathTemplatesEntry
	19, // 22: skyline.api.config.File.BucketsEntry.value:type_name -> skyline.api.config.File.Bucket
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
