// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: shared/user.proto

package sharedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl      string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Phone          string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Gender         int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAtMs    int64                  `protobuf:"varint,10,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAtMs    int64                  `protobuf:"varint,12,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	BannedUntilMs  int64                  `protobuf:"varint,13,opt,name=banned_until_ms,json=bannedUntilMs,proto3" json:"banned_until_ms,omitempty"`
	LastSignInAtMs int64                  `protobuf:"varint,14,opt,name=last_sign_in_at_ms,json=lastSignInAtMs,proto3" json:"last_sign_in_at_ms,omitempty"`
	IsSuperAdmin   bool                   `protobuf:"varint,15,opt,name=is_super_admin,json=isSuperAdmin,proto3" json:"is_super_admin,omitempty"`
	UserMetadata   *UserMetadata          `protobuf:"bytes,21,opt,name=user_metadata,json=userMetadata,proto3" json:"user_metadata,omitempty"`
	AppMetadata    *AppMetadata           `protobuf:"bytes,22,opt,name=app_metadata,json=appMetadata,proto3" json:"app_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_shared_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_shared_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_shared_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *User) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *User) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *User) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *User) GetBannedUntilMs() int64 {
	if x != nil {
		return x.BannedUntilMs
	}
	return 0
}

func (x *User) GetLastSignInAtMs() int64 {
	if x != nil {
		return x.LastSignInAtMs
	}
	return 0
}

func (x *User) GetIsSuperAdmin() bool {
	if x != nil {
		return x.IsSuperAdmin
	}
	return false
}

func (x *User) GetUserMetadata() *UserMetadata {
	if x != nil {
		return x.UserMetadata
	}
	return nil
}

func (x *User) GetAppMetadata() *AppMetadata {
	if x != nil {
		return x.AppMetadata
	}
	return nil
}

type UserMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bio           string                 `protobuf:"bytes,1,opt,name=bio,proto3" json:"bio,omitempty"`
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserMetadata) Reset() {
	*x = UserMetadata{}
	mi := &file_shared_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetadata) ProtoMessage() {}

func (x *UserMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_shared_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetadata.ProtoReflect.Descriptor instead.
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return file_shared_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserMetadata) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserMetadata) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *UserMetadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AppMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppMetadata) Reset() {
	*x = AppMetadata{}
	mi := &file_shared_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppMetadata) ProtoMessage() {}

func (x *AppMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_shared_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppMetadata.ProtoReflect.Descriptor instead.
func (*AppMetadata) Descriptor() ([]byte, []int) {
	return file_shared_user_proto_rawDescGZIP(), []int{2}
}

var File_shared_user_proto protoreflect.FileDescriptor

const file_shared_user_proto_rawDesc = "" +
	"\n" +
	"\x11shared/user.proto\x12\vlynx.shared\x1a\x19google/protobuf/any.proto\"\xcd\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\x12\"\n" +
	"\rcreated_at_ms\x18\n" +
	" \x01(\x03R\vcreatedAtMs\x12\x1d\n" +
	"\n" +
	"updated_by\x18\v \x01(\tR\tupdatedBy\x12\"\n" +
	"\rupdated_at_ms\x18\f \x01(\x03R\vupdatedAtMs\x12&\n" +
	"\x0fbanned_until_ms\x18\r \x01(\x03R\rbannedUntilMs\x12*\n" +
	"\x12last_sign_in_at_ms\x18\x0e \x01(\x03R\x0elastSignInAtMs\x12$\n" +
	"\x0eis_super_admin\x18\x0f \x01(\bR\fisSuperAdmin\x12>\n" +
	"\ruser_metadata\x18\x15 \x01(\v2\x19.lynx.shared.UserMetadataR\fuserMetadata\x12;\n" +
	"\fapp_metadata\x18\x16 \x01(\v2\x18.lynx.shared.AppMetadataR\vappMetadata\"P\n" +
	"\fUserMetadata\x12\x10\n" +
	"\x03bio\x18\x01 \x01(\tR\x03bio\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\r\n" +
	"\vAppMetadataB?Z=github.com/lynx-go/lynx-clean-template/genproto/shared;sharedpbb\x06proto3"

var (
	file_shared_user_proto_rawDescOnce sync.Once
	file_shared_user_proto_rawDescData []byte
)

func file_shared_user_proto_rawDescGZIP() []byte {
	file_shared_user_proto_rawDescOnce.Do(func() {
		file_shared_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_user_proto_rawDesc), len(file_shared_user_proto_rawDesc)))
	})
	return file_shared_user_proto_rawDescData
}

var file_shared_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shared_user_proto_goTypes = []any{
	(*User)(nil),         // 0: lynx.shared.User
	(*UserMetadata)(nil), // 1: lynx.shared.UserMetadata
	(*AppMetadata)(nil),  // 2: lynx.shared.AppMetadata
}
var file_shared_user_proto_depIdxs = []int32{
	1, // 0: lynx.shared.User.user_metadata:type_name -> lynx.shared.UserMetadata
	2, // 1: lynx.shared.User.app_metadata:type_name -> lynx.shared.AppMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shared_user_proto_init() }
func file_shared_user_proto_init() {
	if File_shared_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_user_proto_rawDesc), len(file_shared_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_user_proto_goTypes,
		DependencyIndexes: file_shared_user_proto_depIdxs,
		MessageInfos:      file_shared_user_proto_msgTypes,
	}.Build()
	File_shared_user_proto = out.File
	file_shared_user_proto_goTypes = nil
	file_shared_user_proto_depIdxs = nil
}
