// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx-clean-template/internal/api/eventhandler"
	"github.com/lynx-go/lynx-clean-template/internal/infra/bun/bunrepo"
	"github.com/lynx-go/lynx-clean-template/internal/infra/clients"
	"github.com/lynx-go/lynx-clean-template/internal/infra/server"
)

// Injectors from wire.go:

func wireCLIContext(app lynx.Lynx) (*CLIContext, func(), error) {
	appConfig, err := NewConfiguration(app)
	if err != nil {
		return nil, nil, err
	}
	binder := server.NewKafkaBinderForCLI(appConfig)
	broker := server.NewPubSub(binder)
	publisher := server.NewPublisher(broker)
	helloHandler := eventhandler.NewHelloHandler()
	router := server.NewPubSubRouter(broker, helloHandler)
	v := NewComponents(broker, binder, router)
	v2 := NewComponentBuilders()
	componentBuilderSetFunc := NewComponentBuilderSetFunc()
	dataClients, cleanup, err := clients.NewDataClients(appConfig)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := bunrepo.NewUsersRepo(dataClients)
	onStartHooks := NewOnStarts()
	onStopHooks := NewOnStops()
	cliContext := NewCLIContext(app, publisher, v, v2, componentBuilderSetFunc, usersRepo, onStartHooks, onStopHooks)
	return cliContext, func() {
		cleanup()
	}, nil
}
