// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx-clean-template/internal/api/eventhandler"
	"github.com/lynx-go/lynx-clean-template/internal/infra/bun/bunrepo"
	"github.com/lynx-go/lynx-clean-template/internal/infra/clients"
	"github.com/lynx-go/lynx-clean-template/internal/infra/server"
)

// Injectors from wire.go:

func wireCLIContext(app lynx.App) (*CLIContext, func(), error) {
	bus := NewAppBus(app)
	broker := server.NewPubSub(bus)
	publisher := server.NewPublisher(broker)
	helloHandler := eventhandler.NewHelloHandler()
	router := server.NewPubSubRouter(broker, helloHandler)
	v := NewComponents(router)
	preStartHooks := NewPreStarts()
	preStopHooks := NewPreStops()
	appConfig, err := NewConfiguration(app)
	if err != nil {
		return nil, nil, err
	}
	dataClients, cleanup, err := clients.NewDataClients(appConfig)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := bunrepo.NewUsersRepo(dataClients)
	cliContext := NewCLIContext(app, publisher, v, preStartHooks, preStopHooks, usersRepo)
	return cliContext, func() {
		cleanup()
	}, nil
}
