// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/lynx-go/lynx"
	"github.com/lynx-go/lynx-clean-template/internal/api/eventhandler"
	"github.com/lynx-go/lynx-clean-template/internal/api/grpc"
	"github.com/lynx-go/lynx-clean-template/internal/app"
	"github.com/lynx-go/lynx-clean-template/internal/domain/files"
	"github.com/lynx-go/lynx-clean-template/internal/domain/users"
	"github.com/lynx-go/lynx-clean-template/internal/infra"
	"github.com/lynx-go/lynx-clean-template/internal/infra/bun/bunrepo"
	"github.com/lynx-go/lynx-clean-template/internal/infra/clients"
	"github.com/lynx-go/lynx-clean-template/internal/infra/server"
	"github.com/lynx-go/lynx/boot"
)

import (
	_ "github.com/jackc/pgx/v5/stdlib"
)

// Injectors from wire.go:

func wireBootstrap(app2 lynx.Lynx) (*boot.Bootstrap, func(), error) {
	onStartHooks := NewOnStarts()
	onStopHooks := NewOnStops()
	scheduler, err := server.NewScheduler()
	if err != nil {
		return nil, nil, err
	}
	appConfig, err := NewAppConfig(app2)
	if err != nil {
		return nil, nil, err
	}
	binder := server.NewKafkaBinderForServer(appConfig)
	broker := server.NewPubSub(binder)
	helloHandler := eventhandler.NewHelloHandler()
	router := server.NewPubSubRouter(broker, helloHandler)
	validator := server.NewAuthValidator(appConfig)
	dataClients, cleanup, err := clients.NewDataClients(appConfig)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := bunrepo.NewUsersRepo(dataClients)
	refreshTokensRepo := bunrepo.NewRefreshTokensRepo(dataClients)
	emailVerificationCodesRepo := bunrepo.NewEmailVerificationCodesRepo(dataClients)
	groupsRepo := bunrepo.NewGroupsRepo(dataClients)
	passwordHasher := infra.NewPasswordHasher()
	userService := users.NewUserService(usersRepo, passwordHasher, appConfig)
	publisher := server.NewPublisher(broker)
	eventPublisher := infra.NewDomainEventPublisher(publisher)
	logger := infra.NewDomainLogger()
	emailTemplateRenderer := infra.NewEmailTemplateRenderer()
	emailSender := infra.NewEmailSender()
	account := app.NewAccount(usersRepo, refreshTokensRepo, emailVerificationCodesRepo, appConfig, groupsRepo, userService, eventPublisher, passwordHasher, logger, emailTemplateRenderer, emailSender)
	authService := grpc.NewAuthService(account)
	groups := app.NewGroups(groupsRepo)
	groupsService := grpc.NewGroupsService(groups)
	repoFiles := bunrepo.NewFilesRepo(dataClients)
	fileURLResolver := files.NewURLRenderer(appConfig, repoFiles)
	appUsers := app.NewUsers(usersRepo, fileURLResolver)
	usersService := grpc.NewUsersService(appUsers)
	grpcServer, err := server.NewGRPCServer(app2, appConfig, validator, authService, groupsService, usersService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	grpcGatewayServer, err := server.NewGRPCGatewayServer(app2, appConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v := NewComponents(scheduler, broker, binder, router, grpcServer, grpcGatewayServer)
	v2 := NewComponentBuilders()
	componentBuilderSetFunc := NewComponentBuilderSetFunc(binder)
	bootstrap := boot.New(onStartHooks, onStopHooks, v, v2, componentBuilderSetFunc)
	return bootstrap, func() {
		cleanup()
	}, nil
}
